USE [master]
GO

WHILE EXISTS(select NULL from sys.databases where name='SimpleExtJsPoc')
BEGIN
    DECLARE @SQL varchar(max)
    SELECT @SQL = COALESCE(@SQL,'') + 'Kill ' + Convert(varchar, SPId) + ';'
    FROM MASTER..SysProcesses
    WHERE DBId = DB_ID(N'SimpleExtJsPoc') AND SPId <> @@SPId
    EXEC(@SQL)
    DROP DATABASE [SimpleExtJsPoc]
END
GO

CREATE DATABASE [SimpleExtJsPoc]
GO

ALTER DATABASE [SimpleExtJsPoc] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SimpleExtJsPoc].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SimpleExtJsPoc] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET ARITHABORT OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SimpleExtJsPoc] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SimpleExtJsPoc] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SimpleExtJsPoc] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SimpleExtJsPoc] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET RECOVERY FULL 
GO

ALTER DATABASE [SimpleExtJsPoc] SET  MULTI_USER 
GO

ALTER DATABASE [SimpleExtJsPoc] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SimpleExtJsPoc] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SimpleExtJsPoc] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SimpleExtJsPoc] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SimpleExtJsPoc] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SimpleExtJsPoc] SET QUERY_STORE = OFF
GO

USE [SimpleExtJsPoc]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [SimpleExtJsPoc] SET  READ_WRITE 
GO


