//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleExtjsPoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roster
    {
        public int id { get; set; }
        public Nullable<short> number { get; set; }
        public string pictureUrl { get; set; }
        public string playerName { get; set; }
        public string pos { get; set; }
        public string batArm { get; set; }
        public string throwArm { get; set; }
        public string height { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<short> age { get; set; }
        public Nullable<short> experience { get; set; }
        public string birthplace { get; set; }
        public string college { get; set; }
        public Nullable<long> salary { get; set; }
        public string category { get; set; }
    }
}
